# Generated by Django 3.0.6 on 2020-06-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frist_app', '0002_auto_20200529_0344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
