# Generated by Django 3.0.6 on 2020-06-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frist_app', '0003_auto_20200602_0204'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
